### PR TITLE
Norway bulky update

### PR DESCRIPTION
**Pull request by seawaR**
Bulky update of Norway tests with data up to 2022-09-22.

### CODE REVIEW

**Comment by benubah** [comment]
@seawaR  Using the script I wrote for processing Norway, I found slight differences between the values in your PR and what I get straight from the source. Take a sample of say from `2022-07-01` : the values in the PR are greater than the values I get by 8 for several dates I checked. Compare first five records below

image

image

**Comment by seawaR** [comment]
Yes, as we discussed before they continuously revise past values so it is very likely that the values change from one day to the next. What I propose is to continue updating the values daily and a bulky update every two weeks or once a month.
This is the data that was available on the source the day I made the bulky update.
[norway_full.txt](https://github.com/finddx/FINDCov19TrackerData/files/9647011/norway_full.txt)

**Comment by benubah** [comment]
Yes, I understand and it's surprising. I was just surprised that the data today has lesser values (instead of more) than the data on the 2022-09-22 when the PR was done. Do you understand my confusion? I expected that they added more data and not remove.

I'll double check your data too. But would be nice if you update with today's data and then we close this and switch to your bi-weekly/monthly update mode.

Many thanks!

**Comment by benubah** [comment]
Thanks!

**Pull request merged**
