### PR TITLE
Create  2022-06-07-processed-manually.csv

### PR DESCRIPTION
**Pull request by benubah**
update Australia manually for 2022-06-07 since last updates only fixes it for 2022-06-06

### CODE REVIEW

**Comment by benubah** [comment]
@seawaR can add the other manually processed countries to the file before merging. or can just merge and later add the others

**Comment by benubah** [comment]
This fix for Australia on the 2022-06-07 has been auto-corrected by the workflow run today. 
Closing this PR

**Comment by seawaR** [comment]
I think it is not necessary to add Australia in the manual file for 2022-06-07 as the value was corrected by the automatic process (see [2022-06-07-tests-selenium.csv](https://github.com/finddx/FINDCov19TrackerData/blob/master/automated/selenium/2022-06-07-tests-selenium.csv)).

**Comment by benubah** [comment]
> This fix for Australia on the 2022-06-07 has been auto-corrected by the workflow run today. Closing this PR

@seawaR  I already noted this above. Thanks

**Pull request closed without merging**
